#!/usr/bin/env python3
"""
app.py — Flask web backend for Dubito.
Run:  python3 app.py
Deps: pip install flask   (Flask 3.x is installed)
"""
import importlib
import random
import uuid

from flask import Flask, jsonify, render_template, request

from dubito.player import Player
from dubito.handlers import GameHandler, StatsHandler, generate_player_data
from dubito.game_data import TurnOutput, TurnData
from dubito.core_game import initialize
from bots.manual import rule_based, probability
from bots.llms import claude as claude_bots

app = Flask(__name__)

# ── Bot registry ──────────────────────────────────────────────────────────────

def _try(module, names):
    try:
        m = importlib.import_module(module)
        return {n: getattr(m, n) for n in names if hasattr(m, n)}
    except (ImportError, ModuleNotFoundError):
        return {}

ALL_BOTS: dict[str, type] = {
    "AlwaysTruthful": rule_based.AlwaysTruthful,
    "JustPutCards":   rule_based.JustPutCards,
    "MrDoubt":        rule_based.MrDoubt,
    "MrNoDoubt":      rule_based.MrNoDoubt,
    "RandomBoi":      rule_based.RandomBoi,
    "StefaBot":       rule_based.StefaBot,
    "AdaptyBoi":      probability.AdaptyBoi,
    "SusBoi":         probability.SusBoi,
    "UsualBot":       probability.UsualBot,
    "RiskCounter":    probability.RiskCounter,
    "ClaudeBot":      claude_bots.ClaudeBot,
    **_try("bots.llms.chatgpt", ["ChatGPTBot", "ChatGPT_thinking"]),
    **_try("bots.llms.gemini",  ["GeminiBot"]),
}

# ── In-memory game store ──────────────────────────────────────────────────────

_games: dict[str, dict] = {}

# ── Card name helpers ─────────────────────────────────────────────────────────

NAMES = {0: "★", 1: "A", 2: "2", 3: "3", 4: "4", 5: "5", 6: "6",
         7: "7", 8: "8", 9: "9", 10: "10", 11: "J", 12: "Q", 13: "K"}
LONG  = {0: "Joker", 1: "Ace", 11: "Jack", 12: "Queen", 13: "King"}

def cn(v):  return NAMES.get(v, str(v))
def cln(v): return LONG.get(v, cn(v))


# ── Human player stub ─────────────────────────────────────────────────────────

class HumanPlayer(Player):
    def __init__(self, id: int) -> None:
        super().__init__(id)

    def play(self, p: TurnData) -> TurnOutput:
        raise NotImplementedError("Human player plays via the web UI")

    def add_cards(self, cards: list[int]) -> None:
        # Append received cards in arrival order — no sorting, so the player
        # can see exactly which cards they picked up at the end of their hand.
        self.cards.hand.extend(cards)


# ── Game label helper ─────────────────────────────────────────────────────────

def _lbl(game: dict, p: Player) -> str:
    if isinstance(p, HumanPlayer):
        return "You"
    return p.__class__.__name__ if game["show_names"] else f"Bot {p.id}"


def _display_name(game: dict, p: Player) -> str:
    if isinstance(p, HumanPlayer):
        return "YOU"
    return p.__class__.__name__ if game["show_names"] else f"Bot {p.id}"


# ── Core game logic ───────────────────────────────────────────────────────────

def _snap(game: dict) -> dict:
    """Capture a lightweight snapshot of board + player card counts + human hand."""
    gh = game["gh"]
    all_players = game["all_players"]
    human = game["human"]
    return {
        "board_cards": gh.n_cards_board(),
        "last_n_played": len(gh.board.latests) if gh.board.latests else 0,
        "declared_number": gh.board.number if gh.board.number else None,
        "declared_name": cln(gh.board.number) if gh.board.number else None,
        "is_first_hand": gh.is_first_hand(),
        "players_cards": {str(p.id): len(p.cards) for p in all_players},
        "human_hand": list(human.cards.hand),
    }


def _process_output(game: dict, output: TurnOutput, this_player: Player, prev_player: Player):
    """
    Apply a TurnOutput to the game state.
    Returns (resolve_events, correct_doubt_bool).
    resolve_events is a list of frame dicts (one per message generated by resolution,
    discard, or win — NOT the initial play/doubt announce which the caller creates).
    """
    gh = game["gh"]
    sh = game["sh"]
    is_first = gh.is_first_hand()
    resolve_events: list[dict] = []
    correct_doubt = False

    if isinstance(this_player, HumanPlayer):
        sh.increase_turns_played(this_player, is_first)

    if output.doubt:
        sh.increase_player_doubts(this_player)
        latest_cards = list(gh.get_latest_played_cards())
        revealed = ', '.join(cn(c) for c in latest_cards)
        jokers = gh.jokers_in_latest()
        # Grammar: "You take" vs "Bot X takes"
        takes = "take" if isinstance(this_player, HumanPlayer) else "takes"
        if gh.is_honest() and jokers:
            # Joker protection — only when play is otherwise valid (joker ± matching cards)
            rest = [c for c in gh.get_board() if c != 0]
            this_player.add_cards(rest)
            sh.increase_player_honesty(prev_player)
            gh.reset_board()
            resolve_events.append({
                "msg": (
                    f"Joker! {_lbl(game, prev_player)} played [{revealed}] — protected. "
                    f"{_lbl(game, this_player)} {takes} {len(rest)} card(s)."
                ),
                "event_type": "joker",
                "actor_id": this_player.id,
                "target_id": this_player.id,
                "revealed_cards": latest_cards,
                **_snap(game),
            })
        elif gh.is_honest():
            n = gh.n_cards_board()
            this_player.add_cards(gh.get_board())
            sh.increase_player_honesty(prev_player)
            gh.reset_board()
            resolve_events.append({
                "msg": (
                    f"{_lbl(game, prev_player)} was honest — played [{revealed}]. "
                    f"{_lbl(game, this_player)} takes {n} card(s). Ouch."
                ),
                "event_type": "take_honest",
                "actor_id": this_player.id,
                "target_id": this_player.id,
                "revealed_cards": latest_cards,
                **_snap(game),
            })
        else:
            n = gh.n_cards_board()
            correct_doubt = True
            prev_player.add_cards(gh.get_board())
            sh.increase_player_dishonesty(prev_player)
            gh.reset_board()
            resolve_events.append({
                "msg": (
                    f"{_lbl(game, prev_player)} was bluffing — actually played [{revealed}]. "
                    f"They take {n} card(s). Free turn for {_lbl(game, this_player)}!"
                ),
                "event_type": "take_bluff",
                "actor_id": this_player.id,
                "target_id": prev_player.id,
                "revealed_cards": latest_cards,
                **_snap(game),
            })
    else:
        if is_first:
            val = output.number or 1
            if val == 0:
                pool = gh.board.availables or output.cards
                val = random.choice(pool)
            gh.set_current_number(val)
        gh.set_board_cards(output.cards)

    # Discard phase
    for p in gh.playing_players():
        disc = p.discard_cards()
        if disc:
            gh.set_discarded_cards(disc)
            resolve_events.append({
                "msg": f"{_lbl(game, p)} discards four {cn(disc[0])}s.",
                "event_type": "discard",
                "actor_id": p.id,
                "target_id": p.id,
                **_snap(game),
            })

    # Win check — any playing player can reach 0 cards via the discard phase
    for winner in [p for p in gh.playing_players() if p.has_no_cards()]:
        gh.set_winners(winner)
        resolve_events.append({
            "msg": f"{_lbl(game, winner)} wins!",
            "event_type": "win",
            "actor_id": winner.id,
            "target_id": winner.id,
            **_snap(game),
        })
    if gh.n_playing_players() == 2:
        losers = gh.playing_players()
        resolve_events.append({
            "msg": f"Game over — {_lbl(game, losers[0])} and {_lbl(game, losers[1])} lose!",
            "event_type": "game_over",
            "actor_id": None,
            "target_id": None,
            **_snap(game),
        })

    return resolve_events, correct_doubt


def _advance_bots(game: dict) -> list[dict]:
    """
    Auto-play all consecutive bot turns until it's the human's turn (or game over).
    Returns a list of animation frames, one per message, each carrying a board+player snapshot.
    """
    gh = game["gh"]
    sh = game["sh"]
    human = game["human"]
    all_frames: list[dict] = []

    while True:
        # Check game-over condition
        if gh.n_playing_players() <= 2 or gh.turn.counter >= 1000:
            break

        # Determine next player
        if game["_correct_doubt"]:
            game["_correct_doubt"] = False
            # this_player stays the same (they doubted correctly and play again)
        else:
            game["prev_player"], game["this_player"] = gh.next_turn()

        this_player = game["this_player"]

        if isinstance(this_player, HumanPlayer):
            break

        # Bot plays
        ip = generate_player_data(gh, sh)
        is_first = gh.is_first_hand()
        output = this_player.play(ip)
        sh.increase_turns_played(this_player, gh.is_first_hand())

        if output.doubt:
            # Capture board state BEFORE resolution (board still has prev player's cards)
            pre_snap = _snap(game)
            resolve_events, correct_doubt = _process_output(
                game, output, this_player, game["prev_player"]
            )
            # Doubt action frame uses pre-resolve snapshot so board still shows cards
            doubt_msg = f"{_lbl(game, this_player)} doubts {_lbl(game, game['prev_player'])}!"
            game["messages"].append(doubt_msg)
            all_frames.append({
                "msg": doubt_msg,
                "event_type": "doubt",
                "actor_id": this_player.id,
                "target_id": game["prev_player"].id,
                **pre_snap,
            })
            for e in resolve_events:
                game["messages"].append(e["msg"])
                all_frames.append(e)
        else:
            # Resolve first (sets board cards inside _process_output)
            resolve_events, correct_doubt = _process_output(
                game, output, this_player, game["prev_player"]
            )
            # Play action frame uses post-board snapshot so pile count is already updated
            if is_first:
                play_msg = (
                    f"{_lbl(game, this_player)} plays {len(output.cards)} card(s), "
                    f"declares {cln(output.number)}s."
                )
            else:
                play_msg = (
                    f"{_lbl(game, this_player)} plays {len(output.cards)} card(s) "
                    f"claiming {cln(gh.board.number)}s."
                )
            game["messages"].append(play_msg)
            all_frames.append({
                "msg": play_msg,
                "event_type": "play",
                "actor_id": this_player.id,
                "target_id": None,
                **_snap(game),
            })
            for e in resolve_events:
                game["messages"].append(e["msg"])
                all_frames.append(e)

        game["_correct_doubt"] = correct_doubt

    return all_frames


def _serialize(game: dict) -> dict:
    """Return a JSON-serializable snapshot of the game state."""
    gh = game["gh"]
    human = game["human"]
    all_players = game["all_players"]
    this_player = game["this_player"]
    prev_player = game["prev_player"]
    playing = gh.playing_players()
    winners = gh.get_winners()

    is_game_over = gh.n_playing_players() <= 2 or gh.turn.counter >= 1000
    timed_out = gh.turn.counter >= 1000

    players_info = []
    for p in all_players:
        is_playing = p in playing or p in winners
        players_info.append({
            "id": p.id,
            "display_name": _display_name(game, p),
            "is_human": isinstance(p, HumanPlayer),
            "n_cards": len(p.cards),
            "is_current": p is this_player,
            "is_prev": p is prev_player and p is not this_player,
            "is_playing": is_playing,
        })

    # Standings: winners first (0 cards), then non-winners sorted by card count asc
    winner_set = set(winners)
    non_winners = sorted(
        [p for p in gh.playing_players() if p not in winner_set],
        key=lambda p: len(p.cards),
    )
    standings = []
    for w in winners:
        standings.append({
            "name": _display_name(game, w),
            "bot_type": None if isinstance(w, HumanPlayer) else w.__class__.__name__,
            "cards": 0,
            "is_human": isinstance(w, HumanPlayer),
        })
    for p in non_winners:
        standings.append({
            "name": _display_name(game, p),
            "bot_type": None if isinstance(p, HumanPlayer) else p.__class__.__name__,
            "cards": len(p.cards),
            "is_human": isinstance(p, HumanPlayer),
        })

    return {
        "game_id": game["id"],
        "status": "game_over" if is_game_over else "player_turn",
        "turn": gh.turn.counter,
        "is_first_hand": gh.is_first_hand(),
        "board_cards": gh.n_cards_board(),
        "last_n_played": len(gh.board.latests) if gh.board.latests else 0,
        "declared_number": gh.board.number if gh.board.number else None,
        "declared_name": cln(gh.board.number) if gh.board.number else None,
        "streak": gh.turn.streak,
        "available_numbers": gh.board.availables,
        "hand": list(human.cards.hand),
        "players": players_info,
        "messages": game["messages"],
        "standings": standings,
        "timed_out": timed_out,
    }


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/bots")
def api_bots():
    return jsonify(list(ALL_BOTS.keys()))


@app.route("/api/game", methods=["POST"])
def api_create_game():
    body = request.get_json(force=True)
    n_players  = int(body.get("n_players", 4))
    bot_pool   = body.get("bot_pool", list(ALL_BOTS.keys()))
    show_names = bool(body.get("show_names", True))

    n_players = max(3, min(8, n_players))

    # Build bot pool
    pool = [ALL_BOTS[n] for n in bot_pool if n in ALL_BOTS]
    if not pool:
        pool = list(ALL_BOTS.values())

    human = HumanPlayer(1)
    bots  = [random.choice(pool)(i + 2) for i in range(n_players - 1)]
    all_players = [human] + bots
    random.shuffle(all_players)
    for i, p in enumerate(all_players):
        p.id = i + 1

    initialize(all_players, n_jollies=2)
    gh = GameHandler(all_players=all_players, deck_size=14)
    sh = StatsHandler(all_players=all_players)

    gid = str(uuid.uuid4())[:8]
    game: dict = {
        "id": gid,
        "gh": gh,
        "sh": sh,
        "human": human,
        "all_players": all_players,
        "prev_player": all_players[-1],
        "this_player": all_players[0],
        "show_names": show_names,
        "messages": [],
        "_correct_doubt": False,
    }
    _games[gid] = game

    # Advance bots if first player is a bot
    init_frames = _advance_bots(game)

    result = _serialize(game)
    result["frames"] = init_frames
    return jsonify(result)


@app.route("/api/game/<gid>/play", methods=["POST"])
def api_play(gid: str):
    game = _games.get(gid)
    if not game:
        return jsonify({"error": "game not found"}), 404

    gh    = game["gh"]
    human = game["human"]
    body  = request.get_json(force=True)

    card_indices = sorted(body.get("card_indices", []))
    number       = body.get("number", None)  # only on first hand

    if not card_indices:
        return jsonify({"error": "no cards selected"}), 400

    # Pick cards from human's hand by index (hand is unsorted — indices match display order)
    cards = [human.cards.hand[i] for i in card_indices]
    for i in sorted(card_indices, reverse=True):
        human.cards.hand.pop(i)

    is_first = gh.is_first_hand()

    # Build play message before resolve (number known, board.number set after for is_first)
    if is_first:
        play_msg = f"You play {len(cards)} card(s) and declare {cln(number)}s."
        output = TurnOutput(doubt=False, number=number, cards=cards)
    else:
        play_msg = f"You play {len(cards)} card(s) claiming {cln(gh.board.number)}s."
        output = TurnOutput(doubt=False, number=None, cards=cards)

    # Resolve (sets board cards for play)
    resolve_events, correct_doubt = _process_output(game, output, human, game["prev_player"])

    # Human play frame: snapshot taken after board is updated
    game["messages"].append(play_msg)
    human_frames: list[dict] = [{
        "msg": play_msg,
        "event_type": "play",
        "actor_id": human.id,
        "target_id": None,
        **_snap(game),
    }]
    for e in resolve_events:
        game["messages"].append(e["msg"])
        human_frames.append(e)

    game["_correct_doubt"] = correct_doubt

    bot_frames = _advance_bots(game)
    all_frames = human_frames + bot_frames

    result = _serialize(game)
    result["frames"] = all_frames
    return jsonify(result)


@app.route("/api/game/<gid>/doubt", methods=["POST"])
def api_doubt(gid: str):
    game = _games.get(gid)
    if not game:
        return jsonify({"error": "game not found"}), 404

    gh    = game["gh"]
    human = game["human"]

    if gh.is_first_hand():
        return jsonify({"error": "cannot doubt on first hand"}), 400

    # Snapshot board BEFORE resolution (still shows prev player's cards)
    pre_snap = _snap(game)

    doubt_msg = f"You doubt {_lbl(game, game['prev_player'])}!"
    output = TurnOutput(doubt=True, number=None, cards=None)
    resolve_events, correct_doubt = _process_output(game, output, human, game["prev_player"])

    # Human doubt frame uses pre-resolve snapshot
    game["messages"].append(doubt_msg)
    human_frames: list[dict] = [{
        "msg": doubt_msg,
        "event_type": "doubt",
        "actor_id": human.id,
        "target_id": game["prev_player"].id,
        **pre_snap,
    }]
    for e in resolve_events:
        game["messages"].append(e["msg"])
        human_frames.append(e)

    game["_correct_doubt"] = correct_doubt

    bot_frames = _advance_bots(game)
    all_frames = human_frames + bot_frames

    result = _serialize(game)
    result["frames"] = all_frames
    return jsonify(result)


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    app.run(port=5001, debug=True)
